services:
  feishin:
    container_name: feishin
    image: 'ghcr.io/jeffvli/feishin:latest'
    restart: unless-stopped
    environment:
        - SERVER_NAME=navidrome # pre-defined server name
        - SERVER_LOCK=true # When true AND name/type/url are set, only username/password can be toggled
        - SERVER_TYPE=navidrome # the allowed types are: jellyfin, navidrome, subsonic. These values are case insensitive
        - SERVER_URL=https://feishin.SITE.COM # http://address or https://address
        - REMOTE_URL=https://feishin.SITE.COM # http://address or https://address
        - LEGACY_AUTHENTICATION=false # When SERVER_LOCK is true, sets the legacy (plaintext) authentication flag for Subsonic/OpenSubsonic servers
        - ANALYTICS_DISABLED=true # Set to true to disable Umami analytics tracking
    ports:
        - 9180:9180
        # Alternatively, to restrict to only localhost, - 127.0.0.1:9180:8190
    networks:
    - koito_default
# I guess this network is fine since it's also part of the scorber
# This network I alreayd have in place for my SCROBER. I am using the same navidrome server on a different system via PODMAN so I think it's safe to use this network twice.
networks:
  koito_default:
    external: true