services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.9.2 # 
    container_name: mealie
    restart: always
    ports:
        - "9000:9000" # 
    deploy:
      resources:
        limits:
          memory: 1000M # 
    volumes:
      - /mnt/Docker/mealie/mealie-data:/app/data/
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: America/Chicago
      BASE_URL: https://mealie.SITE.COM
      # Database Settings
      DB_ENGINE: postgres
      POSTGRES_USER: mealie
      POSTGRES_PASSWORD: mealie
      POSTGRES_SERVER: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: mealie
    networks:
      - mealie_default
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: postgres
    image: postgres:17
    restart: always
    volumes:
      - /mnt/Docker/mealie/mealie-pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mealie
      POSTGRES_USER: mealie
      PGUSER: mealie
      POSTGRES_DB: mealie
    networks:
      - mealie_default
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 20s
      retries: 3

networks:
  mealie_default:
    external: true

volumes:
  mealie-data:
  mealie-pgdata: